// This module contains the localized strings for the languages supported by this build.
// 
// The actual code is generated by build scripts, which load

include!(concat!(env!("OUT_DIR"), "/langs/mod.rs"));
